export const SEARCH_CANDIDATE_REQUEST = "SEARCH_CANDIDATE_REQUEST";
export const SEARCH_CANDIDATE_SUCCESS = "SEARCH_CANDIDATE_SUCCESS";
export const SEARCH_CANDIDATE_FAILURE = "SEARCH_CANDIDATE_FAILURE";

export const CATEGORY_CUSTOMIZATION_REQUEST = "CATEGORY_CUSTOMIZATION_REQUEST";
export const CATEGORY_FIELD_CUSTOMIZATION_REQUEST =
  "CATEGORY_FIELD_CUSTOMIZATION_REQUEST";
export const ADD_NEW_CATEGORY_REQUEST = "ADD_NEW_CATEGORY_REQUEST";
export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const CREATE_CANDIDATE_REQUEST = "CREATE_CANDIDATE_REQUEST";
export const CREATE_CANDIDATE_FAILURE = "CREATE_CANDIDATE_FAILURE";
export const CREATE_CANDIDATE_SUCCESS = "CREATE_CANDIDATE_SUCCESS";

export const DOMAIN_FETCH_REQUEST = "DOMAIN_FETCH_REQUEST";
export const DOMAIN_FETCH_SUCCESS = "DOMAIN_FETCH_SUCCESS";
export const DOMAIN_FETCH_FAILURE = "DOMAIN_FETCH_FAILURE";

export const LABEL_FETCH_REQUEST = "LABEL_FETCH_REQUEST";
export const LABEL_FETCH_SUCCESS = "LABEL_FETCH_SUCCESS";
export const LABEL_FETCH_FAILURE = "LABEL_FETCH_FAILURE";

export const FETCH_LABEL_REQUEST = "FETCH_LABEL_REQUEST";
export const FETCH_LABEL_SUCCESS = "FETCH_LABEL_SUCCESS";
export const FETCH_LABEL_FAILURE = "FETCH_LABEL_FAILURE";

export const ADD_LABEL_REQUEST = "ADD_LABEL_REQUEST";
export const ADD_LABEL_SUCCESS = "ADD_LABEL_SUCCESS;";
export const ADD_LABEL_FAILURE = "ADD_LABEL_FAILURE";

export const UPDATE_LABEL_REQUEST = "UPDATE_LABEL_REQUEST";
export const UPDATE_LABEL_SUCCESS = "UPDATE_LABEL_SUCCESS;";
export const UPDATE_LABEL_FAILURE = "UPDATE_LABEL_FAILURE";

export const DELETE_LABEL_REQUEST = "DELETE_LABEL_REQUEST";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS;";
export const DELETE_LABEL_FAILURE = "DELETE_LABEL_FAILURE";
