export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SEARCH_CANDIDATE_REQUEST = "SEARCH_CANDIDATE_REQUEST";
export const SEARCH_CANDIDATE_SUCCESS = "SEARCH_CANDIDATE_SUCCESS";
export const SEARCH_CANDIDATE_FAILURE = "SEARCH_CANDIDATE_FAILURE";

export const CATEGORY_CUSTOMIZATION_REQUEST = "CATEGORY_CUSTOMIZATION_REQUEST";
export const CATEGORY_FIELD_CUSTOMIZATION_REQUEST =
  "CATEGORY_FIELD_CUSTOMIZATION_REQUEST";
export const ADD_NEW_CATEGORY_REQUEST = "ADD_NEW_CATEGORY_REQUEST";

export const CREATE_CANDIDATE_REQUEST = "CREATE_CANDIDATE_REQUEST";
export const CREATE_CANDIDATE_FAILURE = "CREATE_CANDIDATE_FAILURE";
export const CREATE_CANDIDATE_SUCCESS = "CREATE_CANDIDATE_SUCCESS";

export const ADD_SOURCE_TO_CANDIDATE_REQUEST =
  "ADD_SOURCE_TO_CANDIDATE_REQUEST";
export const ADD_SOURCE_TO_CANDIDATE_FAILURE =
  "ADD_SOURCE_TO_CANDIDATE_FAILURE";
export const ADD_SOURCE_TO_CANDIDATE_SUCCESS =
  "ADD_SOURCE_TO_CANDIDATE_SUCCESS";

export const DOMAIN_FETCH_REQUEST = "DOMAIN_FETCH_REQUEST";
export const DOMAIN_FETCH_SUCCESS = "DOMAIN_FETCH_SUCCESS";
export const DOMAIN_FETCH_FAILURE = "DOMAIN_FETCH_FAILURE";

export const LABEL_FETCH_REQUEST = "LABEL_FETCH_REQUEST";
export const LABEL_FETCH_SUCCESS = "LABEL_FETCH_SUCCESS";
export const LABEL_FETCH_FAILURE = "LABEL_FETCH_FAILURE";

export const FETCH_LABEL_REQUEST = "FETCH_LABEL_REQUEST";
export const FETCH_LABEL_SUCCESS = "FETCH_LABEL_SUCCESS";
export const FETCH_LABEL_FAILURE = "FETCH_LABEL_FAILURE";

export const ADD_LABEL_REQUEST = "ADD_LABEL_REQUEST";
export const ADD_LABEL_SUCCESS = "ADD_LABEL_SUCCESS;";
export const ADD_LABEL_FAILURE = "ADD_LABEL_FAILURE";

export const UPDATE_LABEL_REQUEST = "UPDATE_LABEL_REQUEST";
export const UPDATE_LABEL_SUCCESS = "UPDATE_LABEL_SUCCESS;";
export const UPDATE_LABEL_FAILURE = "UPDATE_LABEL_FAILURE";

export const DELETE_LABEL_REQUEST = "DELETE_LABEL_REQUEST";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS;";
export const DELETE_LABEL_FAILURE = "DELETE_LABEL_FAILURE";

export const FETCH_DOMAIN_REQUEST = "FETCH_DOMAIN_REQUEST";
export const FETCH_DOMAIN_SUCCESS = "FETCH_DOMAIN_SUCCESS";
export const FETCH_DOMAIN_FAILURE = "FETCH_DOMAIN_FAILURE";

export const ADD_DOMAIN_REQUEST = "ADD_DOMAIN_REQUEST";
export const ADD_DOMAIN_SUCCESS = "ADD_DOMAIN_SUCCESS;";
export const ADD_DOMAIN_FAILURE = "ADD_DOMAIN_FAILURE";

export const UPDATE_DOMAIN_REQUEST = "UPDATE_DOMAIN_REQUEST";
export const UPDATE_DOMAIN_SUCCESS = "UPDATE_DOMAIN_SUCCESS;";
export const UPDATE_DOMAIN_FAILURE = "UPDATE_DOMAIN_FAILURE";

export const DELETE_DOMAIN_REQUEST = "DELETE_DOMAIN_REQUEST";
export const DELETE_DOMAIN_SUCCESS = "DELETE_DOMAIN_SUCCESS;";
export const DELETE_DOMAIN_FAILURE = "DELETE_DOMAIN_FAILURE";

export const FETCH_CANDIDATES_REQUEST = "FETCH_CANDIDATES_REQUEST";
export const FETCH_CANDIDATES_SUCCESS = "FETCH_CANDIDATES_SUCCESS";
export const FETCH_CANDIDATES_FAILURE = "FETCH_CANDIDATES_FAILURE";

export const CANDIDATE_DETAILS_REQUEST = "CANDIDATE_DETAILS_REQUEST";
export const CANDIDATE_DETAILS_SUCCESS = "CANDIDATE_DETAILS_SUCCESS";
export const CANDIDATE_DETAILS_FAILURE = "CANDIDATE_DETAILS_FAILURE";

export const EXTRACT_RESUME_REQUEST = "EXTRACT_RESUME_REQUEST";
export const EXTRACT_RESUME_SUCCESS = "EXTRACT_RESUME_SUCCESS";
export const EXTRACT_RESUME_FAILURE = "EXTRACT_RESUME_FAILURE";

export const FETCH_ARCHIVE_CANDIDATES_REQUEST =
  "FETCH_ARCHIVE_CANDIDATES_REQUEST";
export const FETCH_ARCHIVE_CANDIDATES_SUCCESS =
  "FETCH_ARCHIVE_CANDIDATES_SUCCESS";
export const FETCH_ARCHIVE_CANDIDATES_FAILURE =
  "FETCH_ARCHIVE_CANDIDATES_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_CANDIDATE_DETAILS_REQUEST =
  "UPDATE_CANDIDATE_DETAILS_REQUEST";
export const UPDATE_CANDIDATE_DETAILS_SUCCESS =
  "UPDATE_CANDIDATE_DETAILS_SUCCESS";
export const UPDATE_CANDIDATE_DETAILS_FAILURE =
  "UPDATE_CANDIDATE_DETAILS_FAILURE";

export const UPDATE_CANDIDATE_LABEL_REQUEST = "UPDATE_CANDIDATE_LABEL_REQUEST";
export const UPDATE_CANDIDATE_LABEL_SUCCESS = "UPDATE_CANDIDATE_LABEL_SUCCESS";
export const UPDATE_CANDIDATE_LABEL_FAILURE = "UPDATE_CANDIDATE_LABEL_FAILURE";

export const FETCH_SUGGESTED_FOLDER_REQUEST = "FETCH_SUGGESTED_FOLDER_REQUEST";
export const FETCH_SUGGESTED_FOLDER_SUCCESS = "FETCH_SUGGESTED_FOLDER_SUCCESS";
export const FETCH_SUGGESTED_FOLDER_FAILURE = "FETCH_SUGGESTED_FOLDER_FAILURE";

export const FETCH_ALL_CATEGORIES_REQUEST = "FETCH_ALL_CATEGORIES_REQUEST";
export const FETCH_ALL_CATEGORIES_SUCCESS = "FETCH_ALL_CATEGORIES_SUCCESS";
export const FETCH_ALL_CATEGORIES_FAILURE = "FETCH_ALL_CATEGORIES_FAILURE";

export const REORDER_CATEGORIES_REQUEST = "REORDER_CATEGORIES_REQUEST";
export const REORDER_CATEGORIES_SUCCESS = "REORDER_CATEGORIES_SUCCESS";
export const REORDER_CATEGORIES_FAILURE = "REORDER_CATEGORIES_FAILURE";

export const ARCHIVE_CANDIDATES_SUCCESS = "ARCHIVE_CANDIDATES_SUCCESS";
export const ARCHIVE_CANDIDATES_REQUEST = "ARCHIVE_CANDIDATES_REQUEST";
export const ARCHIVE_CANDIDATES_FAILURE = "ARCHIVE_CANDIDATES_FAILURE";

export const REORDER_CATEGORIRY_FIELD_REQUEST =
  "REORDER_CATEGORIRY_FIELD_REQUEST";
export const REORDER_CATEGORIRY_FIELD_SUCCESS =
  "REORDER_CATEGORIRY_FIELD_SUCCESS";
export const REORDER_CATEGORIRY_FIELD_FAILURE =
  "REORDER_CATEGORIRY_FIELD_FAILURE";

export const FETCH_COLUMNS_LIST_REQUEST = "FETCH_COLUMNS_LIST_REQUEST";
export const FETCH_COLUMNS_LIST_SUCCESS = "FETCH_COLUMNS_LIST_SUCCESS";
export const FETCH_COLUMNS_LIST_FAILURE = "FETCH_COLUMNS_LIST_FAILURE";

export const UPDATE_COLUMNS_LIST_REQUEST = "UPDATE_COLUMNS_LIST_REQUEST";
export const UPDATE_COLUMNS_LIST_SUCCESS = "UPDATE_COLUMNS_LIST_SUCCESS";
export const UPDATE_COLUMNS_LIST_FAILURE = "UPDATE_COLUMNS_LIST_FAILURE";

export const DELETE_CANDIDATE_REQUEST = "DELETE_CANDIDATE_REQUEST";
export const DELETE_CANDIDATE_SUCCESS = "DELETE_CANDIDATE_SUCCESS";
export const DELETE_CANDIDATE_FAILURE = "DELETE_CANDIDATE_FAILURE";

export const RESTORE_CANDIDATE_REQUEST = "RESTORE_CANDIDATE_REQUEST";
export const RESTORE_CANDIDATE_SUCCESS = "RESTORE_CANDIDATE_SUCCESS";
export const RESTORE_CANDIDATE_FAILURE = "RESTORE_CANDIDATE_FAILURE";

export const FETCH_CANDIDATE_SUMMARY_REQUEST =
  "FETCH_CANDIDATE_SUMMARY_REQUEST";
export const FETCH_CANDIDATE_SUMMARY_SUCCESS =
  "FETCH_CANDIDATE_SUMMARY_SUCCESS";
export const FETCH_CANDIDATE_SUMMARY_FAILURE =
  "FETCH_CANDIDATE_SUMMARY_FAILURE";

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE";

export const HIDE_CATEGORY_REQUEST = "HIDE_CATEGORY_REQUEST";
export const HIDE_CATEGORY_SUCCESS = "HIDE_CATEGORY_SUCCESS";
export const HIDE_CATEGORY_FAILURE = "HIDE_CATEGORY_FAILURE";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILURE = "UPDATE_CATEGORY_FAILURE";

export const DELETE_CATEGORY_FIELD_REQUEST = "DELETE_CATEGORY_FIELD_REQUEST";
export const DELETE_CATEGORY_FIELD_SUCCESS = "DELETE_CATEGORY_FIELD_SUCCESS";
export const DELETE_CATEGORY_FIELD_FAILURE = "DELETE_CATEGORY_FIELD_FAILURE";

export const HIDE_CATEGORY_FIELD_REQUEST = "HIDE_CATEGORY_FIELD_REQUEST";
export const HIDE_CATEGORY_FIELD_SUCCESS = "HIDE_CATEGORY_FIELD_SUCCESS";
export const HIDE_CATEGORY_FIELD_FAILURE = "HIDE_CATEGORY_FIELD_FAILURE";

export const ADD_CATEGORY_FIELD_REQUEST = "ADD_CATEGORY_FIELD_REQUEST";
export const ADD_CATEGORY_FIELD_SUCCESS = "ADD_CATEGORY_FIELD_SUCCESS";
export const ADD_CATEGORY_FIELD_FAILURE = "ADD_CATEGORY_FIELD_FAILURE";

export const UPDATE_CATEGORY_FIELD_REQUEST = "UPDATE_CATEGORY_FIELD_REQUEST";
export const UPDATE_CATEGORY_FIELD_SUCCESS = "UPDATE_CATEGORY_FIELD_SUCCESS";
export const UPDATE_CATEGORY_FIELD_FAILURE = "UPDATE_CATEGORY_FIELD_FAILURE";

export const ADD_ATTACHMENTS_REQUEST = "ADD_ATTACHMENTS_REQUEST";
export const ADD_ATTACHMENTS_SUCCESS = "ADD_ATTACHMENTS_SUCCESS";
export const ADD_ATTACHMENTS_FAILURE = "ADD_ATTACHMENTS_FAILURE";

export const UPLOAD_ATTACHMENT_REQUEST = "UPLOAD_ATTACHMENT_REQUEST";
export const UPLOAD_ATTACHMENT_SUCCESS = "UPLOAD_ATTACHMENT_SUCCESS";
export const UPLOAD_ATTACHMENT_FAILURE = "UPLOAD_ATTACHMENT_FAILURE";

export const UPLOAD_PROFILE_REQUEST = "UPLOAD_PROFILE_REQUEST";
export const UPLOAD_PROFILE_SUCCESS = "UPLOAD_PROFILE_SUCCESS";
export const UPLOAD_PROFILE_FAILURE = "UPLOAD_PROFILE_FAILURE";
