export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SEARCH_CANDIDATE_REQUEST = "SEARCH_CANDIDATE_REQUEST";
export const SEARCH_CANDIDATE_SUCCESS = "SEARCH_CANDIDATE_SUCCESS";
export const SEARCH_CANDIDATE_FAILURE = "SEARCH_CANDIDATE_FAILURE";

export const CATEGORY_CUSTOMIZATION_REQUEST = "CATEGORY_CUSTOMIZATION_REQUEST";
export const CATEGORY_FIELD_CUSTOMIZATION_REQUEST =
  "CATEGORY_FIELD_CUSTOMIZATION_REQUEST";
export const ADD_NEW_CATEGORY_REQUEST = "ADD_NEW_CATEGORY_REQUEST";

export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";

export const CREATE_CANDIDATE_REQUEST = "CREATE_CANDIDATE_REQUEST";
export const CREATE_CANDIDATE_FAILURE = "CREATE_CANDIDATE_FAILURE";
export const CREATE_CANDIDATE_SUCCESS = "CREATE_CANDIDATE_SUCCESS";

export const ADD_SOURCE_TO_CANDIDATE_REQUEST =
  "ADD_SOURCE_TO_CANDIDATE_REQUEST";
export const ADD_SOURCE_TO_CANDIDATE_FAILURE =
  "ADD_SOURCE_TO_CANDIDATE_FAILURE";
export const ADD_SOURCE_TO_CANDIDATE_SUCCESS =
  "ADD_SOURCE_TO_CANDIDATE_SUCCESS";

export const DOMAIN_FETCH_REQUEST = "DOMAIN_FETCH_REQUEST";
export const DOMAIN_FETCH_SUCCESS = "DOMAIN_FETCH_SUCCESS";
export const DOMAIN_FETCH_FAILURE = "DOMAIN_FETCH_FAILURE";

export const LABEL_FETCH_REQUEST = "LABEL_FETCH_REQUEST";
export const LABEL_FETCH_SUCCESS = "LABEL_FETCH_SUCCESS";
export const LABEL_FETCH_FAILURE = "LABEL_FETCH_FAILURE";

export const FETCH_LABEL_REQUEST = "FETCH_LABEL_REQUEST";
export const FETCH_LABEL_SUCCESS = "FETCH_LABEL_SUCCESS";
export const FETCH_LABEL_FAILURE = "FETCH_LABEL_FAILURE";

export const ADD_LABEL_REQUEST = "ADD_LABEL_REQUEST";
export const ADD_LABEL_SUCCESS = "ADD_LABEL_SUCCESS;";
export const ADD_LABEL_FAILURE = "ADD_LABEL_FAILURE";

export const UPDATE_LABEL_REQUEST = "UPDATE_LABEL_REQUEST";
export const UPDATE_LABEL_SUCCESS = "UPDATE_LABEL_SUCCESS;";
export const UPDATE_LABEL_FAILURE = "UPDATE_LABEL_FAILURE";

export const DELETE_LABEL_REQUEST = "DELETE_LABEL_REQUEST";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS;";
export const DELETE_LABEL_FAILURE = "DELETE_LABEL_FAILURE";

export const FETCH_DOMAIN_REQUEST = "FETCH_DOMAIN_REQUEST";
export const FETCH_DOMAIN_SUCCESS = "FETCH_DOMAIN_SUCCESS";
export const FETCH_DOMAIN_FAILURE = "FETCH_DOMAIN_FAILURE";

export const ADD_DOMAIN_REQUEST = "ADD_DOMAIN_REQUEST";
export const ADD_DOMAIN_SUCCESS = "ADD_DOMAIN_SUCCESS;";
export const ADD_DOMAIN_FAILURE = "ADD_DOMAIN_FAILURE";

export const UPDATE_DOMAIN_REQUEST = "UPDATE_DOMAIN_REQUEST";
export const UPDATE_DOMAIN_SUCCESS = "UPDATE_DOMAIN_SUCCESS;";
export const UPDATE_DOMAIN_FAILURE = "UPDATE_DOMAIN_FAILURE";

export const DELETE_DOMAIN_REQUEST = "DELETE_DOMAIN_REQUEST";
export const DELETE_DOMAIN_SUCCESS = "DELETE_DOMAIN_SUCCESS;";
export const DELETE_DOMAIN_FAILURE = "DELETE_DOMAIN_FAILURE";

export const FETCH_CANDIDATES_REQUEST = "FETCH_CANDIDATES_REQUEST";
export const FETCH_CANDIDATES_SUCCESS = "FETCH_CANDIDATES_SUCCESS";
export const FETCH_CANDIDATES_FAILURE = "FETCH_CANDIDATES_FAILURE";

export const CANDIDATE_DETAILS_REQUEST = "CANDIDATE_DETAILS_REQUEST";
export const CANDIDATE_DETAILS_SUCCESS = "CANDIDATE_DETAILS_SUCCESS";
export const CANDIDATE_DETAILS_FAILURE = "CANDIDATE_DETAILS_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_CANDIDATE_DETAILS_REQUEST =
  "UPDATE_CANDIDATE_DETAILS_REQUEST";
export const UPDATE_CANDIDATE_DETAILS_SUCCESS =
  "UPDATE_CANDIDATE_DETAILS_SUCCESS";
export const UPDATE_CANDIDATE_DETAILS_FAILURE =
  "UPDATE_CANDIDATE_DETAILS_FAILURE";
