export const candidates = [
    {
       id: 1,
       candidate_name: "Larry Joseph",
        candidate_first_name: "Larry",
        candidate_last_name: "Joseph",
        reference_id: "REF001",
        location: "Saraborough, Central African Republic",
        gender: "Female",
        diploma: "Engineering",
       university: "Watson-Shaw",
       current_company: "Reyes, Tran and Thompson",
        current_position: "Financial Analyst",
        email: "russowanda@hicks-mcintyre.com",
        birthDate: "1999-04-19",
        candidate_address: "4621 Miguel Island\nWrightborough, AZ 62178",
        employment_status: "Employed",
        phone: "(477)705-2878",
        hired_date: "2021-01-20",
        start_date: "2024-10-14",
      
        created_at: "2021-12-08",
       created_by: "HR Consultant"
    },
    {
       id: 2,
       candidate_name: "Kerri Stewart",
        candidate_first_name: "Kerri",
        candidate_last_name: "Stewart",
        reference_id: "REF002",
        location: "East Daniel, Samoa",
        gender: "Male",
        diploma: "Computer Science",
       university: "Bailey, Martinez and Yoder",
       current_company: "Gillespie, Henry and Nguyen",
        current_position: "Data Analyst",
        email: "jonathanlopez@erickson-lewis.com",
        birthDate: "1984-04-26",
        candidate_address: "0200 Dominguez Causeway Suite 566\nLake Mercedesside, RI 72125",
    
        phone: "973-358-7275",
        hired_date: "2023-05-26",
        start_date: "2020-03-09",
       ats_score: 59,
        created_at: "2023-09-18",
       created_by: "Recruiter"
    },
    {
       id: 3,
       candidate_name: "Christina Vasquez",
        candidate_first_name: "Christina",
        candidate_last_name: "Vasquez",
        reference_id: "REF003",
        location: "Danielfort, Western Sahara",
        gender: "Female",
        diploma: "Computer Science",
       university: "Poole-Snyder",
       current_company: "Wilson, Hill and Mendoza",
        current_position: "Marketing Manager",
        email: "ncastro@tran.com",
        birthDate: "1976-10-09",
        candidate_address: "32631 Eric Parkways\nSouth Robin, WY 04223",
        employment_status: "Employed",
        phone: "(570)342-7726x75254",
        hired_date: "2024-08-18",
        start_date: "2022-07-22",
       ats_score: 57,
        created_at: "2024-02-15",
       created_by: "HR Specialist"
    },
    {
       id: 4,
       candidate_name: "Kristine Brown",
        candidate_first_name: "Kristine",
        candidate_last_name: "Brown",
        reference_id: "REF004",
        location: "New Lindafort, Cuba",
        gender: "Male",
        diploma: "Information Technology",
       university: "Mayer-Spencer",
       current_company: "Robinson-Alvarez",
        current_position: "Data Analyst",
        email: "mrivera@gmail.com",
        birthDate: "1982-03-18",
        candidate_address: "20248 Mosley Street\nLake Troyhaven, TN 45693",
        employment_status: "Unemployed",
        phone: "144-987-0966x838",
        hired_date: "2021-12-17",
        start_date: "2021-01-23",
       ats_score: 80,
        created_at: "2023-02-20",
       created_by: "HR Consultant"
    },
    {
       id: 5,
       candidate_name: "Tami Rios",
        candidate_first_name: "Tami",
        candidate_last_name: "Rios",
        reference_id: "REF005",
        location: "Teresachester, Namibia",
        gender: "Male",
        diploma: "Marketing",
       university: "Anderson PLC",
       current_company: "Long Group",
        current_position: "Data Analyst",
        email: "robert00@hotmail.com",
        birthDate: "1983-02-23",
        candidate_address: "061 Bryan Junction\nNew Lisa, TX 12760",
        employment_status: "Unemployed",
        phone: "001-576-468-1122x9247",
        hired_date: "2022-06-16",
        start_date: "2025-01-16",
       ats_score: 64,
        created_at: "2024-08-22",
       created_by: "HR Manager"
    },
    {
       id: 6,
       candidate_name: "Tracy Patrick",
        candidate_first_name: "Tracy",
        candidate_last_name: "Patrick",
        reference_id: "REF006",
        location: "West Timothy, Tanzania",
        gender: "Male",
        diploma: "Marketing",
       university: "Cooper-Gonzalez",
       current_company: "Martinez-Sims",
        current_position: "Backend Developer",
        email: "chenhailey@hotmail.com",
        birthDate: "1994-01-19",
        candidate_address: "81992 Horton Rest\nGlassfurt, MD 85093",
        employment_status: "Unemployed",
        phone: "046.942.2780x723",
        hired_date: "2021-10-11",
        start_date: "2023-03-22",
       ats_score: 83,
        created_at: "2025-02-01",
       created_by: "HR Manager"
    },
    {
       id: 7,
       candidate_name: "Kenneth Sullivan",
        candidate_first_name: "Kenneth",
        candidate_last_name: "Sullivan",
        reference_id: "REF007",
        location: "Tammybury, Algeria",
        gender: "Male",
        diploma: "Engineering",
       university: "Wong-Johnson",
       current_company: "Bishop, Sloan and Anderson",
        current_position: "Software Engineer",
        email: "uwalker@yahoo.com",
        birthDate: "1990-06-16",
        candidate_address: "9050 Meyers Brook\nSouth Alanstad, DC 48449",
        employment_status: "Unemployed",
        phone: "(427)516-3094x4575",
        hired_date: "2023-10-26",
        start_date: "2024-09-27",
       ats_score: 94,
        created_at: "2024-10-05",
       created_by: "Recruiter"
    },
    {
       id: 8,
       candidate_name: "Nicole Young",
        candidate_first_name: "Nicole",
        candidate_last_name: "Young",
        reference_id: "REF008",
        location: "Lake Jason, Sri Lanka",
        gender: "Male",
        diploma: "Computer Science",
       university: "Hernandez LLC",
       current_company: "Hill Ltd",
        current_position: "Financial Analyst",
        email: "navarrodawn@yahoo.com",
        birthDate: "1974-02-27",
        candidate_address: "86981 Kelly Unions Apt. 565\nWestport, CA 12263",
        employment_status: "Unemployed",
        phone: "001-518-597-9122x68889",
        hired_date: "2022-10-28",
        start_date: "2021-12-09",
       ats_score: 90,
        created_at: "2023-02-15",
       created_by: "HR Manager"
    },
    {
       id: 9,
       candidate_name: "Ricky Rice",
        candidate_first_name: "Ricky",
        candidate_last_name: "Rice",
        reference_id: "REF009",
        location: "South Gary, Slovenia",
        gender: "Male",
        diploma: "Marketing",
       university: "Hernandez and Sons",
       current_company: "Murphy Group",
        current_position: "Backend Developer",
        email: "ycolon@welch.net",
        birthDate: "1979-10-16",
        candidate_address: "PSC 6435, Box 1753\nAPO AA 48817",
        employment_status: "Unemployed",
        phone: "(028)009-8423",
        hired_date: "2020-10-01",
        start_date: "2023-11-29",
       ats_score: 64,
        created_at: "2020-01-04",
       created_by: "Recruiter"
    },
    {
       id: 10,
       candidate_name: "Barbara Cox",
        candidate_first_name: "Barbara",
        candidate_last_name: "Cox",
        reference_id: "REF010",
        location: "Port Monicaville, Namibia",
        gender: "Male",
        diploma: "Finance",
       university: "Ballard-Rose",
       current_company: "White Group",
        current_position: "Financial Analyst",
        email: "qcurtis@yahoo.com",
        birthDate: "2001-12-09",
        candidate_address: "099 Brenda Glen Suite 692\nHayesville, MO 10875",
        employment_status: "Unemployed",
        phone: "442.452.8274x04867",
        hired_date: "2021-02-07",
        start_date: "2021-03-22",
       ats_score: 94,
        created_at: "2022-08-28",
       created_by: "HR Specialist"
    },
    {
       id: 11,
       candidate_name: "Aaron Mooney",
        candidate_first_name: "Aaron",
        candidate_last_name: "Mooney",
        reference_id: "REF011",
        location: "Burtonborough, Mauritania",
        gender: "Female",
        diploma: "Finance",
       university: "Lopez-Mercado",
       current_company: "Johnson-Mcdonald",
        current_position: "Marketing Manager",
        email: "sierralopez@knight.com",
        birthDate: "1999-08-04",
        candidate_address: "5676 Pena Extensions Apt. 217\nNorth Kristen, DE 79445",
        employment_status: "Unemployed",
        phone: "(669)843-2845",
        hired_date: "2023-12-21",
        start_date: "2020-02-17",
       ats_score: 79,
        created_at: "2021-03-19",
       created_by: "Recruiter"
    },
    {
       id: 12,
       candidate_name: "Linda Parrish",
        candidate_first_name: "Linda",
        candidate_last_name: "Parrish",
        reference_id: "REF012",
        location: "Port Rebecca, Malawi",
        gender: "Male",
        diploma: "Computer Science",
       university: "Watson, Petty and Coleman",
       current_company: "Mendez, Bolton and Roth",
        current_position: "Software Engineer",
        email: "omurphy@lee.org",
        birthDate: "1999-01-12",
        candidate_address: "58036 Robinson Camp Apt. 702\nEast Jenniferstad, TX 28837",
        employment_status: "Unemployed",
        phone: "001-557-356-4027x701",
        hired_date: "2024-10-02",
        start_date: "2022-01-06",
       ats_score: 93,
        created_at: "2022-05-27",
       created_by: "HR Consultant"
    },
    {
       id: 13,
       candidate_name: "Julie Robertson",
        candidate_first_name: "Julie",
        candidate_last_name: "Robertson",
        reference_id: "REF013",
        location: "Walterberg, Palestinian Territory",
        gender: "Male",
        diploma: "Marketing",
       university: "Rodriguez, Drake and Crosby",
       current_company: "Hawkins, Burton and Lee",
        current_position: "Software Engineer",
        email: "robinsonamber@hotmail.com",
        birthDate: "2002-11-16",
        candidate_address: "614 Rachel Parkways Apt. 221\nGonzalezfort, ME 70377",
        employment_status: "Employed",
        phone: "325.729.7290x697",
        hired_date: "2021-12-13",
        start_date: "2020-05-16",
       ats_score: 83,
        created_at: "2023-10-15",
       created_by: "HR Manager"
    },
    {
       id: 14,
       candidate_name: "David Mccann",
        candidate_first_name: "David",
        candidate_last_name: "Mccann",
        reference_id: "REF014",
        location: "Romeroville, Myanmar",
        gender: "Male",
        diploma: "Engineering",
       university: "Gonzalez-Daniels",
       current_company: "Vargas, Miller and Lee",
        current_position: "Software Engineer",
        email: "nwilliams@hotmail.com",
        birthDate: "1993-01-02",
        candidate_address: "703 Terrence Shores Apt. 727\nAliciamouth, NV 18765",
        employment_status: "Unemployed",
        phone: "+1-852-754-9531",
        hired_date: "2024-05-22",
        start_date: "2024-07-08",
       ats_score: 63,
        created_at: "2021-06-25",
       created_by: "HR Specialist"
    },
    {
       id: 15,
       candidate_name: "Erin Henderson",
        candidate_first_name: "Erin",
        candidate_last_name: "Henderson",
        reference_id: "REF015",
        location: "Currymouth, Korea",
        gender: "Female",
        diploma: "Marketing",
       university: "Rodriguez Ltd",
       current_company: "Taylor Inc",
        current_position: "Data Analyst",
        email: "toniellison@gray.net",
        birthDate: "1997-09-23",
        candidate_address: "81514 Odom Throughway\nNorth Scott, ID 36569",
        employment_status: "Unemployed",
        phone: "141.667.6390x178",
        hired_date: "2021-10-04",
        start_date: "2022-05-03",
       ats_score: 90,
        created_at: "2021-10-01",
       created_by: "Recruiter"
    },
    {
       id: 16,
       candidate_name: "Tiffany Frederick",
        candidate_first_name: "Tiffany",
        candidate_last_name: "Frederick",
        reference_id: "REF016",
        location: "Selenahaven, Heard Island and McDonald Islands",
        gender: "Female",
        diploma: "Finance",
       university: "Rodriguez LLC",
       current_company: "Joseph PLC",
        current_position: "Financial Analyst",
        email: "xjames@gmail.com",
        birthDate: "1984-03-24",
        candidate_address: "8573 Patricia Spring Suite 859\nLake Kaylashire, SC 22328",
        employment_status: "Employed",
        phone: "001-913-591-5753x31628",
        hired_date: "2020-10-25",
        start_date: "2024-06-16",
       ats_score: 76,
        created_at: "2024-07-31",
       created_by: "HR Consultant"
    },
    {
       id: 17,
       candidate_name: "Tyler Hall",
        candidate_first_name: "Tyler",
        candidate_last_name: "Hall",
        reference_id: "REF017",
        location: "Hawkinschester, Togo",
        gender: "Female",
        diploma: "Marketing",
       university: "Berry-Jimenez",
       current_company: "Bailey PLC",
        current_position: "Marketing Manager",
        email: "graykaren@martin.info",
        birthDate: "1983-09-17",
        candidate_address: "58138 Christopher Land\nLaurenbury, NY 36851",
        employment_status: "Employed",
        phone: "763-304-4393x323",
        hired_date: "2024-08-16",
        start_date: "2020-05-27",
       ats_score: 76,
        created_at: "2021-07-18",
       created_by: "Recruiter"
    },
    {
       id: 18,
       candidate_name: "Cody Cook",
        candidate_first_name: "Cody",
        candidate_last_name: "Cook",
        reference_id: "REF018",
        location: "Jonathanview, Somalia",
        gender: "Female",
        diploma: "Marketing",
       university: "Sanders-Nguyen",
       current_company: "Jackson-Nguyen",
        current_position: "Data Analyst",
        email: "sethwade@evans.biz",
        birthDate: "1994-10-12",
        candidate_address: "3857 David Crossing\nAmandaville, SC 45965",
        employment_status: "Unemployed",
        phone: "1552740204",
        hired_date: "2024-03-28",
        start_date: "2021-07-09",
       ats_score: 79,
        created_at: "2021-04-09",
       created_by: "HR Specialist"
    },
    {
       id: 19,
       candidate_name: "Beverly Blair",
        candidate_first_name: "Beverly",
        candidate_last_name: "Blair",
        reference_id: "REF019",
        location: "Port Melissa, Macao",
        gender: "Female",
        diploma: "Information Technology",
       university: "Mason, Roberts and Ball",
       current_company: "Davis LLC",
        current_position: "Marketing Manager",
        email: "justinhenry@choi.com",
        birthDate: "1974-12-30",
        candidate_address: "USNV Guzman\nFPO AP 85116",
        employment_status: "Unemployed",
        phone: "376-747-8149x81007",
        hired_date: "2024-10-29",
        start_date: "2020-06-03",
       ats_score: 88,
        created_at: "2022-06-08",
       created_by: "HR Consultant"
    },
    {
       id: 20,
       candidate_name: "Ashley Marshall",
        candidate_first_name: "Ashley",
        candidate_last_name: "Marshall",
        reference_id: "REF020",
        location: "East Aaronhaven, Oman",
        gender: "Male",
        diploma: "Information Technology",
       university: "Cline-Rodriguez",
       current_company: "Coffey-Vazquez",
        current_position: "Financial Analyst",
        email: "mccoyann@hotmail.com",
        birthDate: "1980-10-28",
        candidate_address: "9889 Martinez Shores\nRonaldstad, KY 66216",
        employment_status: "Employed",
        phone: "001-827-100-1285x89757",
        hired_date: "2024-12-18",
        start_date: "2023-08-13",
       ats_score: 71,
        created_at: "2022-10-07",
       created_by: "Recruiter"
    },
    {
       id: 21,
       candidate_name: "Jessica Cordova",
        candidate_first_name: "Jessica",
        candidate_last_name: "Cordova",
        reference_id: "REF021",
        location: "Jeremychester, Congo",
        gender: "Male",
        diploma: "Finance",
       university: "Sweeney PLC",
       current_company: "Hoover-Nelson",
        current_position: "Marketing Manager",
        email: "jthompson@yahoo.com",
        birthDate: "1979-11-08",
        candidate_address: "969 Jodi Parkway Suite 586\nSouth Wandaberg, TN 14586",
        employment_status: "Unemployed",
        phone: "649-045-9931x410",
        hired_date: "2024-06-18",
        start_date: "2023-04-04",
       ats_score: 88,
        created_at: "2023-06-25",
       created_by: "HR Specialist"
    },
    {
       id: 22,
       candidate_name: "Mitchell Hudson",
        candidate_first_name: "Mitchell",
        candidate_last_name: "Hudson",
        reference_id: "REF022",
        location: "New Phillipchester, Belgium",
        gender: "Female",
        diploma: "Finance",
       university: "Norman, Turner and Fletcher",
       current_company: "Medina-Martin",
        current_position: "Financial Analyst",
        email: "marshrobert@gutierrez-sanders.com",
        birthDate: "1986-01-25",
        candidate_address: "79436 Timothy Rue\nTammyton, MA 86927",
        employment_status: "Employed",
        phone: "001-013-086-5006x26805",
        hired_date: "2020-06-14",
        start_date: "2024-12-05",
       ats_score: 78,
        created_at: "2021-10-08",
       created_by: "HR Specialist"
    },
    {
       id: 23,
       candidate_name: "Cindy Martin",
        candidate_first_name: "Cindy",
        candidate_last_name: "Martin",
        reference_id: "REF023",
        location: "Lake Seth, Wallis and Futuna",
        gender: "Male",
        diploma: "Finance",
       university: "Lowe-Walker",
       current_company: "Hawkins-Hunter",
        current_position: "Software Engineer",
        email: "amandagreen@rollins-watts.com",
        birthDate: "1978-03-15",
        candidate_address: "870 Paul Cliffs\nDanielleberg, CA 23080",
        employment_status: "Employed",
        phone: "165-460-1607",
        hired_date: "2020-09-25",
        start_date: "2025-02-03",
       ats_score: 81,
        created_at: "2021-08-18",
       created_by: "HR Specialist"
    },
    {
       id: 24,
       candidate_name: "Henry Bond",
        candidate_first_name: "Henry",
        candidate_last_name: "Bond",
        reference_id: "REF024",
        location: "North Benjamin, Sao Tome and Principe",
        gender: "Female",
        diploma: "Marketing",
       university: "King, Spencer and Wood",
       current_company: "Davidson Ltd",
        current_position: "Data Analyst",
        email: "kbowers@jones.com",
        birthDate: "1997-03-02",
        candidate_address: "26160 Orozco Pass Apt. 346\nRussellton, AZ 84709",
        employment_status: "Employed",
        phone: "+1-543-983-8009x52462",
        hired_date: "2021-11-02",
        start_date: "2022-01-29",
       ats_score: 52,
        created_at: "2024-11-28",
       created_by: "HR Consultant"
    },
    {
       id: 25,
       candidate_name: "Briana Miller",
        candidate_first_name: "Briana",
        candidate_last_name: "Miller",
        reference_id: "REF025",
        location: "Port Saramouth, French Polynesia",
        gender: "Male",
        diploma: "Computer Science",
       university: "Ramirez, Flynn and Valdez",
       current_company: "Cline, Bowen and Berg",
        current_position: "Marketing Manager",
        email: "kellydestiny@flores.com",
        birthDate: "1991-07-09",
        candidate_address: "319 Mora Keys Suite 853\nEast Robertborough, AK 16695",
        employment_status: "Employed",
        phone: "+1-983-906-2437",
        hired_date: "2020-06-26",
        start_date: "2020-12-18",
       ats_score: 96,
        created_at: "2020-06-26",
       created_by: "Recruiter"
    },
    {
       id: 26,
       candidate_name: "John Vaughn",
        candidate_first_name: "John",
        candidate_last_name: "Vaughn",
        reference_id: "REF026",
        location: "Hutchinsonland, Latvia",
        gender: "Female",
        diploma: "Computer Science",
       university: "Blankenship-Parker",
       current_company: "Scott, Gardner and Douglas",
        current_position: "Software Engineer",
        email: "paulhobbs@hotmail.com",
        birthDate: "1992-02-20",
        candidate_address: "4947 Peck Ville\nNew Erica, GA 62165",
        employment_status: "Unemployed",
        phone: "+1-680-607-3591",
        hired_date: "2020-06-23",
        start_date: "2023-06-29",
       ats_score: 83,
        created_at: "2024-01-26",
       created_by: "HR Consultant"
    },
    {
       id: 27,
       candidate_name: "Christopher Reese",
        candidate_first_name: "Christopher",
        candidate_last_name: "Reese",
        reference_id: "REF027",
        location: "Ericbury, Mexico",
        gender: "Female",
        diploma: "Finance",
       university: "Avila Inc",
       current_company: "Diaz, Cruz and Thomas",
        current_position: "Data Analyst",
        email: "gwalker@cannon.biz",
        birthDate: "1994-12-28",
        candidate_address: "013 Mata Fords Apt. 104\nPort Donnaton, DE 96513",
        employment_status: "Unemployed",
        phone: "(779)657-5092",
        hired_date: "2024-10-19",
        start_date: "2023-06-06",
       ats_score: 95,
        created_at: "2023-08-04",
       created_by: "HR Manager"
    },
    {
       id: 28,
       candidate_name: "Patrick Garcia",
        candidate_first_name: "Patrick",
        candidate_last_name: "Garcia",
        reference_id: "REF028",
        location: "Michaelburgh, Heard Island and McDonald Islands",
        gender: "Female",
        diploma: "Computer Science",
       university: "Oconnor-Tapia",
       current_company: "Thompson Ltd",
        current_position: "Financial Analyst",
        email: "rmendoza@hotmail.com",
        birthDate: "1990-05-01",
        candidate_address: "7229 Stacy Plaza\nStaceyview, CT 56060",
        employment_status: "Unemployed",
        phone: "+1-560-905-0730x77040",
        hired_date: "2023-10-16",
        start_date: "2023-03-05",
       ats_score: 64,
        created_at: "2021-07-13",
       created_by: "HR Consultant"
    },
    {
       id: 29,
       candidate_name: "Melissa Brown",
        candidate_first_name: "Melissa",
        candidate_last_name: "Brown",
        reference_id: "REF029",
        location: "Kempland, Thailand",
        gender: "Female",
        diploma: "Computer Science",
       university: "Stewart, King and Miller",
       current_company: "Richards-Dyer",
        current_position: "Financial Analyst",
        email: "taylormichael@yahoo.com",
        birthDate: "1994-08-13",
        candidate_address: "4260 Kara Run Apt. 726\nSouth Vanessaside, CO 90096",
        employment_status: "Unemployed",
        phone: "442-733-3968x9983",
        hired_date: "2024-10-16",
        start_date: "2020-07-22",
       ats_score: 93,
        created_at: "2020-07-26",
       created_by: "HR Specialist"
    },
    {
       id: 30,
       candidate_name: "Rebecca Perez",
        candidate_first_name: "Rebecca",
        candidate_last_name: "Perez",
        reference_id: "REF030",
        location: "Paigeport, Bahamas",
        gender: "Female",
        diploma: "Computer Science",
       university: "Smith, Brown and Taylor",
       current_company: "Marsh-Jackson",
        current_position: "Data Analyst",
        email: "cwade@cole-schultz.net",
        birthDate: "1981-01-04",
        candidate_address: "398 Cameron Pine\nEast Wayne, IN 67116",
        employment_status: "Unemployed",
        phone: "926-404-1264",
        hired_date: "2021-07-30",
        start_date: "2022-06-10",
       ats_score: 50,
        created_at: "2022-05-04",
       created_by: "HR Manager"
    },
    {
       id: 31,
       candidate_name: "Andrea Manning",
        candidate_first_name: "Andrea",
        candidate_last_name: "Manning",
        reference_id: "REF031",
        location: "North Debrastad, Central African Republic",
        gender: "Female",
        diploma: "Finance",
       university: "Peterson-Morgan",
       current_company: "Cooke Inc",
        current_position: "Data Analyst",
        email: "aowens@yahoo.com",
        birthDate: "1976-09-30",
        candidate_address: "5189 Jeremiah Court Apt. 260\nKnoxtown, OH 10828",
        employment_status: "Unemployed",
        phone: "+1-320-531-5701x829",
        hired_date: "2022-06-03",
        start_date: "2023-07-25",
       ats_score: 82,
        created_at: "2023-10-18",
       created_by: "HR Consultant"
    },
    {
       id: 32,
       candidate_name: "Melvin Davis",
        candidate_first_name: "Melvin",
        candidate_last_name: "Davis",
        reference_id: "REF032",
        location: "Seanview, Tokelau",
        gender: "Female",
        diploma: "Information Technology",
       university: "Reed, Howard and Smith",
       current_company: "Johnson-Gonzalez",
        current_position: "Financial Analyst",
        email: "kayla78@johnston.com",
        birthDate: "1986-05-05",
        candidate_address: "6459 Michael Station Suite 904\nLake Kenneth, TN 37378",
        employment_status: "Employed",
        phone: "252-624-4350x199",
        hired_date: "2022-09-25",
        start_date: "2022-12-30",
       ats_score: 54,
        created_at: "2021-07-06",
       created_by: "HR Consultant"
    },
    {
       id: 33,
       candidate_name: "Juan Bush",
        candidate_first_name: "Juan",
        candidate_last_name: "Bush",
        reference_id: "REF033",
        location: "Colleenchester, Chad",
        gender: "Female",
        diploma: "Information Technology",
       university: "Parker LLC",
       current_company: "Bennett-Case",
        current_position: "Backend Developer",
        email: "fmartin@yahoo.com",
        birthDate: "1980-11-16",
        candidate_address: "09476 Reeves Meadow\nBrandonshire, GA 01305",
        employment_status: "Employed",
        phone: "001-432-201-8629x48415",
        hired_date: "2021-02-28",
        start_date: "2021-05-12",
       ats_score: 94,
        created_at: "2021-08-26",
       created_by: "Recruiter"
    },
    {
       id: 34,
       candidate_name: "Michael Orozco",
        candidate_first_name: "Michael",
        candidate_last_name: "Orozco",
        reference_id: "REF034",
        location: "Lake Jonathanport, Liberia",
        gender: "Female",
        diploma: "Marketing",
       university: "Riley, Freeman and Daniel",
       current_company: "Morris-Adams",
        current_position: "Financial Analyst",
        email: "jamesmorris@gmail.com",
        birthDate: "2002-11-27",
        candidate_address: "56510 Larson Cape\nEast Francisco, TX 78034",
        employment_status: "Employed",
        phone: "337.460.7735x06879",
        hired_date: "2023-06-20",
        start_date: "2023-08-17",
       ats_score: 99,
        created_at: "2022-06-17",
       created_by: "HR Consultant"
    },
    {
       id: 35,
       candidate_name: "Madison Hicks",
        candidate_first_name: "Madison",
        candidate_last_name: "Hicks",
        reference_id: "REF035",
        location: "Petersfurt, Mozambique",
        gender: "Male",
        diploma: "Computer Science",
       university: "James Group",
       current_company: "Thornton, Key and Gonzalez",
        current_position: "Backend Developer",
        email: "beniteztyrone@olson-garrison.com",
        birthDate: "1990-07-02",
        candidate_address: "557 Andrew Point Suite 627\nReneeton, ME 08874",
        employment_status: "Unemployed",
        phone: "936-971-7809",
        hired_date: "2020-04-06",
        start_date: "2021-12-12",
       ats_score: 78,
        created_at: "2024-06-09",
       created_by: "HR Specialist"
    },
    {
       id: 36,
       candidate_name: "Stephen Alexander",
        candidate_first_name: "Stephen",
        candidate_last_name: "Alexander",
        reference_id: "REF036",
        location: "Bridgetside, Saint Pierre and Miquelon",
        gender: "Male",
        diploma: "Information Technology",
       university: "Cummings and Sons",
       current_company: "Gonzales-Leblanc",
        current_position: "Software Engineer",
        email: "kimberlywood@richardson.com",
        birthDate: "1975-07-07",
        candidate_address: "1829 Murphy Lock\nHoffmanport, OR 34382",
        employment_status: "Unemployed",
        phone: "881-723-6173",
        hired_date: "2020-12-10",
        start_date: "2022-11-22",
       ats_score: 92,
        created_at: "2023-03-29",
       created_by: "HR Consultant"
    },
    {
       id: 37,
       candidate_name: "Jean Cook",
        candidate_first_name: "Jean",
        candidate_last_name: "Cook",
        reference_id: "REF037",
        location: "Tylerhaven, Saint Kitts and Nevis",
        gender: "Female",
        diploma: "Finance",
       university: "Krause-Fisher",
       current_company: "Fischer and Sons",
        current_position: "Software Engineer",
        email: "michael55@hotmail.com",
        birthDate: "1982-03-14",
        candidate_address: "63343 Michael Common Suite 476\nRiverastad, OH 27526",
        employment_status: "Unemployed",
        phone: "701.200.3524",
        hired_date: "2024-08-15",
        start_date: "2023-11-27",
       ats_score: 50,
        created_at: "2023-09-26",
       created_by: "HR Consultant"
    },
    {
       id: 38,
       candidate_name: "Ariel Gonzalez",
        candidate_first_name: "Ariel",
        candidate_last_name: "Gonzalez",
        reference_id: "REF038",
        location: "North Travis, Croatia",
        gender: "Male",
        diploma: "Information Technology",
       university: "Sanford-Morales",
       current_company: "Nelson, Adams and Nichols",
        current_position: "Data Analyst",
        email: "uvalencia@hotmail.com",
        birthDate: "1980-09-25",
        candidate_address: "851 Shelby Station\nEast Brittany, ND 48173",
        employment_status: "Unemployed",
        phone: "767-464-8269x48796",
        hired_date: "2023-11-04",
        start_date: "2020-12-06",
       ats_score: 88,
        created_at: "2022-01-23",
       created_by: "HR Consultant"
    },
    {
       id: 39,
       candidate_name: "Deborah Mccarthy",
        candidate_first_name: "Deborah",
        candidate_last_name: "Mccarthy",
        reference_id: "REF039",
        location: "New Courtney, United Arab Emirates",
        gender: "Female",
        diploma: "Information Technology",
       university: "Lindsey-Nelson",
       current_company: "Glover, Garrison and Kirby",
        current_position: "Financial Analyst",
        email: "dana36@wiley.com",
        birthDate: "1984-06-11",
        candidate_address: "2269 Joshua Heights\nJohnsonport, CT 67617",
        employment_status: "Employed",
        phone: "332-837-7354",
        hired_date: "2022-09-29",
        start_date: "2024-04-21",
       ats_score: 83,
        created_at: "2023-10-01",
       created_by: "HR Manager"
    },
    {
        id: 40,
        candidate_name: "Mary Spencer",
        candidate_first_name: "Mary",
        candidate_last_name: "Spencer",
        reference_id: "REF040",
        location: "Port Jessica, Burkina Faso",
        gender: "Male",
        diploma: "Computer Science",
       university: "Eaton, Nguyen and Johnson",
       current_company: "Copeland LLC",
        current_position: "Backend Developer",
        email: "schmittmolly@yahoo.com",
        birthDate: "1998-08-27",
        candidate_address: "8247 Caleb Park Suite 988\nSouth Brandon, IN 67323",
        employment_status: "Unemployed",
        phone: "250-407-5951x72117",
        hired_date: "2024-05-03",
        start_date: "2022-02-04",
       ats_score: 62,
        created_at: "2022-03-19",
       created_by: "HR Consultant"
    }
]

export const archivedCandidates = [
   {
       "id": 1,
       "candidate_name": "David Brown",
       "owner": "Manager",
       "archived_date": "2024-05-01"
   },
   {
       "id": 2,
       "candidate_name": "Jack Smith",
       "owner": "Supervisor",
       "archived_date": "2024-05-09"
   },
   {
       "id": 3,
       "candidate_name": "Isaac White",
       "owner": "Lead",
       "archived_date": "2024-08-03"
   },
   {
       "id": 4,
       "candidate_name": "Charlie Brown",
       "owner": "Owner3",
       "archived_date": "2024-09-07"
   },
   {
       "id": 5,
       "candidate_name": "Isaac Smith",
       "owner": "Supervisor",
       "archived_date": "2024-07-24"
   },
   {
       "id": 6,
       "candidate_name": "Hannah Anderson",
       "owner": "Owner2",
       "archived_date": "2024-08-31"
   },
   {
       "id": 7,
       "candidate_name": "Emma Martin",
       "owner": "Manager",
       "archived_date": "2024-06-18"
   },
   {
       "id": 8,
       "candidate_name": "Jack Thomas",
       "owner": "Manager",
       "archived_date": "2025-02-02"
   },
   {
       "id": 9,
       "candidate_name": "Hannah Brown",
       "owner": "Owner2",
       "archived_date": "2024-07-27"
   },
   {
       "id": 10,
       "candidate_name": "Isaac Jackson",
       "owner": "Lead",
       "archived_date": "2024-05-08"
   },
   {
       "id": 11,
       "candidate_name": "Alice Jackson",
       "owner": "HR",
       "archived_date": "2024-03-11"
   },
   {
       "id": 12,
       "candidate_name": "George Thomas",
       "owner": "Owner1",
       "archived_date": "2024-06-18"
   },
   {
       "id": 13,
       "candidate_name": "Fiona Harris",
       "owner": "Owner1",
       "archived_date": "2024-12-06"
   },
   {
       "id": 14,
       "candidate_name": "David White",
       "owner": "HR",
       "archived_date": "2024-08-24"
   },
   {
       "id": 15,
       "candidate_name": "Bob Taylor",
       "owner": "Owner1",
       "archived_date": "2024-11-24"
   },
   {
       "id": 16,
       "candidate_name": "Bob White",
       "owner": "Manager",
       "archived_date": "2024-08-20"
   },
   {
       "id": 17,
       "candidate_name": "Alice Brown",
       "owner": "Owner1",
       "archived_date": "2024-09-28"
   },
   {
       "id": 18,
       "candidate_name": "Hannah Taylor",
       "owner": "Coordinator",
       "archived_date": "2024-10-25"
   },
   {
       "id": 19,
       "candidate_name": "Jack Taylor",
       "owner": "Lead",
       "archived_date": "2024-04-22"
   },
   {
       "id": 20,
       "candidate_name": "David Smith",
       "owner": "Recruiter",
       "archived_date": "2024-08-25"
   },
   {
       "id": 21,
       "candidate_name": "David Johnson",
       "owner": "Lead",
       "archived_date": "2024-04-20"
   },
   {
       "id": 22,
       "candidate_name": "Charlie Smith",
       "owner": "Admin",
       "archived_date": "2024-08-26"
   },
   {
       "id": 23,
       "candidate_name": "David Harris",
       "owner": "Recruiter",
       "archived_date": "2024-09-10"
   },
   {
       "id": 24,
       "candidate_name": "Alice Taylor",
       "owner": "Owner1",
       "archived_date": "2024-12-14"
   },
   {
       "id": 25,
       "candidate_name": "Charlie Taylor",
       "owner": "Supervisor",
       "archived_date": "2024-07-13"
   },
   {
       "id": 26,
       "candidate_name": "Isaac Thomas",
       "owner": "Manager",
       "archived_date": "2024-07-08"
   },
   {
       "id": 27,
       "candidate_name": "Alice Brown",
       "owner": "Recruiter",
       "archived_date": "2024-10-30"
   },
   {
       "id": 28,
       "candidate_name": "Bob Anderson",
       "owner": "Manager",
       "archived_date": "2024-10-13"
   },
   {
       "id": 29,
       "candidate_name": "Emma Smith",
       "owner": "Coordinator",
       "archived_date": "2024-03-28"
   },
   {
       "id": 30,
       "candidate_name": "Isaac White",
       "owner": "Recruiter",
       "archived_date": "2024-08-11"
   },
   {
       "id": 31,
       "candidate_name": "Hannah Johnson",
       "owner": "Recruiter",
       "archived_date": "2024-11-02"
   },
   {
       "id": 32,
       "candidate_name": "Fiona Anderson",
       "owner": "HR",
       "archived_date": "2024-04-14"
   },
   {
       "id": 33,
       "candidate_name": "Charlie Smith",
       "owner": "HR",
       "archived_date": "2024-03-15"
   },
   {
       "id": 34,
       "candidate_name": "Bob Jackson",
       "owner": "HR",
       "archived_date": "2024-11-24"
   },
   {
       "id": 35,
       "candidate_name": "Jack Harris",
       "owner": "Recruiter",
       "archived_date": "2024-03-30"
   },
   {
       "id": 36,
       "candidate_name": "Bob Smith",
       "owner": "Recruiter",
       "archived_date": "2025-01-31"
   },
   {
       "id": 37,
       "candidate_name": "Emma Jackson",
       "owner": "Owner2",
       "archived_date": "2025-02-11"
   },
   {
       "id": 38,
       "candidate_name": "Bob Johnson",
       "owner": "Owner1",
       "archived_date": "2024-10-02"
   },
   {
       "id": 39,
       "candidate_name": "Isaac Brown",
       "owner": "Recruiter",
       "archived_date": "2024-11-14"
   },
   {
       "id": 40,
       "candidate_name": "Fiona Brown",
       "owner": "Owner3",
       "archived_date": "2024-03-29"
   }
]
export const foldersCandidates = [
    {
        "id": 1,
        "folder_name": "David Brown",
        "candidate_count":"10",
        "create-on": "2024-05-01",
        "create_by": "updiser"
    },
    {
        "id": 2,
        "folder_name": "Jack Smith",
        "candidate_count":"10",
        "create-on": "2024-05-09",
        "create_by": "updiser"
    },
    {
        "id": 3,
        "folder_name": "Isaac White",
        "candidate_count":"10",
        "create-on": "2024-08-03",
        "create_by": "updiser"
    },
    {
        "id": 4,
        "folder_name": "Charlie Brown",
        "candidate_count":"10",
        "create-on": "2024-09-07",
        "create_by": "updiser"
    },
    {
        "id": 5,
        "folder_name": "Isaac Smith",
        "candidate_count":"10",
        "create-on": "2024-07-24",
        "create_by": "updiser"
    },
    {
        "id": 6,
        "folder_name": "Hannah Anderson",
        "candidate_count":"10",
        "create-on": "2024-08-31",
        "create_by": "updiser"
    },
    {
        "id": 7,
        "folder_name": "Emma Martin",
        "candidate_count":"10",
        "create-on": "2024-06-18",
        "create_by": "updiser"
    },
    {
        "id": 8,
        "folder_name": "Jack Thomas",
        "candidate_count":"10",
        "create-on": "2025-02-02",
        "create_by": "updiser"
    },
    
 ]